### ISSUE TITLE
NPM package is not built

### ISSUE THREAD

**Issue by davisshaver** [Dhaiwat10/priv-key-precommit#9]
`npm i priv-key-precommit` results in a folder with the following files: `package.json` and `readme.md`. The NPM publish process does not appear to be working correctly.

**Comment by Dhaiwat10** [comment]
hey @davisshaver everything seems to be working fine for me. can you share a repo link or any more info?

**Comment by Dhaiwat10** [comment]
also just as a sidenote, pls install this package as a dev dependency

**Comment by Dhaiwat10** [comment]
https://www.runpkg.com/?priv-key-precommit@0.3.4/dist/index.js

**Comment by davisshaver** [comment]
thanks @Dhaiwat10! 0.3.4 worked for me. I didn't see the `dist` folder in 0.3.3.
